### PR TITLE
Added GSP Schematics

### PR DESCRIPTION
**Pull request by eliaskountouris**
Some changes need to still be made to the schematics, but I wanted to put them up so the converter / LDO circuits can be reviewed asap.

Changes still needed to be made:
- Cap sizes for each line need to be determined, I could use some help here
- Mb we want to add reverse polarity protection?
- Need to add M12 + USB + fan connectors, will get this done asap

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/infrastructure/3)

### CODE REVIEW

**Comment by Rio6** [comment]
1. What's the reason for using isolated dc-dc converters? Also, the output ground (0V pin) are floating, which means their Vout are floating. If isolation is required for some reason, then connect battery to seperate ground and connect 0V to normal ground. Otherwise just connect the two grounds together.

2. What are the LDOs at the output of switching regulators for? The max dropout voltage for LD1085 is 1.5V max, so supplying 5V to 5V LDO or 12V to 12V LDO will not produce the desired output. Is there any problem to use the output of dc-dc directly? Also, LDOs in parallel are undesired, they can fight each other over tiny amount of voltage difference.

**Comment by Rio6** [comment]
The converters are kinda costy to me, but maybe others with more sourcing experience can comment on the price range.

**Review by rdakhil — DISMISSED** [review]

**Review by rdakhil — CHANGES_REQUESTED** [review]
1. you should annotate all the symbols so they have reference designators

2. it would also be nice to have the datasheets linked to all the parts

3. why do you have LDOs after your switching regulators? generally this is only done for power rails that must be low-noise, eg. power for analog circuits

4. as Rio mentioned, the LDOs have something called a dropout voltage, which is the minimum voltage difference between the input and the output. The LD1085V50 has a typical dropout voltage of 1.3V, meaning that the input must be at least 1.3V higher than its output (5V). Thus, the input voltage must be at least 6.3V for your LDO to work properly

5. Actually, 1.3V is quite high of a dropout voltage for an LDO (usually they are below 1V, as low as 100mV). If you do want to use an LDO after the switching regulator to have a low-noise power rail, then consider finding an LDO with a lower dropout voltage. this means the LDO will be more efficient, since your input voltage can be closer to your output voltage, and efficiency of an LDO is calculated by Vin/Vout

6.  would be good to note the output voltage of VRB1205YMD-15WR3 on the schematic

7. what is the input voltage to LM1085IT-12 from that connector? it would be good to note that on the schematic

8. why are there two LM1085IT-12 with their outputs connected? do you need to double the current output? generally, directly connecting the output of two LDOs is a bad idea. this is because they will not both be outputting exactly 12V, but rather in reality they will be within a set voltage range (datasheet says 11.76V to 12.24V), thus it is highly unlikely that they will be outputting exactly the same voltage. if one LDO is operating at a higher voltage than the other, one will be providing more current than the other up to its current limit which may cause the LDO to shutdown/drop in voltage. 

here is a good explanation of how you can connect two LDOs in parallel: https://www.analog.com/en/technical-articles/paralleling-linear-regulators-made-easy.html
however, it's probably best to just find an LDO with a higher current output so you only have to use one

9. need a GND symbol here: 
image

10. What is the output voltage of URB2424LD-30WR3? it would be good to note, just to confirm that the input voltage of L7824CD2T is high enough that its dropout voltage isn't being violated (like in my point #4)

11. It would also be good to note your battery voltage range

12. is there a specific reason why we are using isolated switching regulators? they are quite expensive, and require a much higher input capacitance (100uF input is a lot) due to them having an internal transformer instead of an inductor. they are also less efficient, meaning more power will be dissipated and your batteries will drain faster than if you were using a nonisolated switching regulator

13. in terms of the capacitor on the output of your battery line here:
image
i assume you want a bulk capacitor here instead of decoupling/bypass capacitor (since you already have them on the inputs of all your power regulators, which filter out high frequency noise). for bulk capacitors, you want their value to be larger than the total capacitance of the rail connected to it (currently you have 100uF x 2 = 200uF on the output of your battery line, so your bulk capacitor should be higher in value)

14. in terms of the capacitors on your voltage rails here:
image
i assume you are using them as bypass capacitors to filter out noise. the value depends on whether or not you want to filter out high frequency noise or low frequency noise. since there are switching regulators on the board, i assume you want to filter out high frequency noise. therefore, you should choose a low value capacitor, like 0.1uF. if you want to filter out both high + low frequency, you could have 0.1uF in parallel with 1uF. might be overkill though. 

quick explanation: basically, for a bypass capacitor, you want your caps to provide a low impedance path for high frequency currents so that they go to ground instead of through the ICs connected to that rail. for a given impedance (lower than the impedance of whatever is on your output), capacitance is inversely proportional to frequency. Thus, for a high frequency signal, you need a lower value capacitor to provide that low impedance path. for a low freq signal, you will need a higher value capacitor.

15. i like that you have the power budget on the schematic, very nice

I said a lot here so please feel free to DM me on slack if you need clarification or have any questions about anything in my review!

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
A good start, but there are some miscommunications to resolve:
(Also sorry for repeating stuff I started on this before seeing randy and rio's reviews)

1. We don't really care about getting super clean voltage out of this thing, anything that needs a very clean voltage (aka DAQ) has its own circuitry to provide that from a noisy rail.
  a) We don't need the LDOs, just the bucks / boosts and their noisy output is totally fine.
  b) With the exception of within DAQ, whenever we refer to a 12V line of this team we really are talking about the raw battery voltage, be that 14V or 9V. So there's no need for the 12v buck/boost, we can just hook up the battery directly. We use the raw battery voltage instead of regulating it because it means we don't need some expensive high current regulator to drive a motor that doesn't actually care about its input voltage and just needs a lot of power. RLCS will see peak draws of like 8A (when going to safe state / actuating multiple valves at once), that's way easier to handle with direct wires to a battery.
2. Your power budget is out of date.
  a) 5V is not current used by anything but will be useful to power things like gopros / picams / phones via USB. RLCS regulates its own 5V down from 12V.
  b) RLCS will draw ~200 mA on the 12V line nominally and peak up to maybe 8A or 12A (actuators are _very_ roughly 4A)
3. I don't see a way to take in 120VAC / switch between power sources? Note that you shouldn't actually make your PCB deal with 120VAC but you should source a 120VAC -> 12V supply with the required power, mount it in the briefcase, and add screw terminals for the regulated input.
4. Likewise it's probably a good idea to expose multiple (3?) connectors for parallelized car batteries. Easier to have 3 battery connectors and "join them up" on the PCB then have 1 connector and do the parallelization with wires.
5. Reverse polarity protection is a good idea. Probably easiest to do with a relay given the current draw?
6. On the topic of isolated converters, they are also not a great idea since everything downstream expects a common ground (there is only one ground wire in the 4-pin M12 after all)!

I think we've dumped enough info at you that it's not valuable to nitpick at this point, looking forward to the next revision.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking much better, nice work!

1. I would highly recommend against these AC/DC converters with screw terminals for AC input, the then have exposed 120VAC and doing our own AC wiring is not advisable. There are lots of cheap ATX power supplies that can do the required wattage, you'll want the 24-pin motherboard connector on the PCB to connect up to it and short those wires it requires to turn on (google for details)
2. Having these screw terminals wired up like this just makes me think youve made a wiring mistake, much more clear to use two 3-position screw terminals if you want to expose 3 GNDs and 3 powers.
image
3. That reverse polarity mosfat comes in a package with a massive ground pad that is going to be hellish to solder, I think a through-hole relay with a diode in series with the coil is an easier solution here.
4. Your symbol for the 5V regulator doesn't have enough pins (the actual module also has CTRL and Trim pins, not to mention all the duplicate pins). Even if they should be left NC you should explicitly show that on the schematic.
5. The 24V regulator you selected is single-output not dual-output (notice the +- in the white boxes). Thus your symbol is incorrect, the 6th pin is a trim pin instead.
image
6. RLCS does not have bulk capacitors.
7. 8 AWG wire would be _way_ overkill. Wire gauge calculators will give you sizes that can handle that much current continuously, but RLCS is only drawing a small amount continuously. So probably size for something large but managable, and it will just heat up a tad when RLCS actuates.
8. I think it would probably be easiest to actually build the array of M12 connectors into this PCB. You can get through-hole vertical ones and then mount the PCB against one of the briefcase walls so all the connectors poke through.
9.  Don't forget current monitoring + DAQ connections.
10. The main power switch will probably end up connecting via screw terminals, but if you've sourced a board mount one that happens to line up with the M12 connectors then that works too. Also probably better to notate it as a SP3T switch, is a third "off" position.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Nice, looking good! Notes:

1. You should add the standard PC motherboard connector for your AC/DC input. PC power supplies only turn on when an enable pin is connected, so you can do that while also having a convenient way to plug in the supply without needing to make up a custom harness. Do note that the standard connector doesn't expose that many 12v pins, so you might want to add the standard CPU or GPU power connectors too for the required current. Look at the PSU datasheet to figure out what connectors you need exactly.
2. You have a 3PST switch where the third position is off, and then you separately have an on/off switch. Redundant, no?
3. Current sensing is not done correctly. You need to put the shunt resistor _in series_ with the load.
4. Why do the voltage sensing dividers use the CURR netlables and not the actual power rails?
5. The CURR netlabels are local - they won't connect across different sheets. You should use hierarchical (preferred) or global labels to connect between sheets. 
6. I'd at at least 3-4 more M12 breakouts for future expansion. We don't necessarily need to buy connectors for them yet but having them available without respinning the PCB would be nice.
7. Rather than using global labels for your _UNREGULATED labels you should be using netlabels, or even better just a direct wire connection (keeps things readable for 1:1 connections)
8. How did you calculate for a 200 mF capacitor? That seems hard to source and scarily large
9. I think your K7805 symbol is still wrong since the real thing has way more than 6 pins. Also currenty kicad things the footprint is SOT-23-6 lol.

**Comment by BluCodeGH** [comment]
Sorry for all the back and forth on this one, it's a decently complex system where we're dealing with a lot of power and I want to make sure we get it right.

1. You also need to add the standard 24 pin connector in order for the power supply to turn on. Also looks like the AGV650 is out of stock everywhere so you'll need to use a different model. I'd recommend the Thermaltake Smart 430W (found via pcpartpicker) since its a name brand and decently cheap.
2. You have a 3PST switch where the third position is off, and then you separately have an on/off switch. Redundant, no?
3. No need for a GND screw terminal going to the 3PST switch. Also I think it would be better here to merge all the 1-pin screw terminals into a ring terminal connector, something like this:
image
4. Your battery terminals are all connected to +VDD which will hook them up directly to the AC/DC supply. You want the 3PST switch in between the two.
image
5. Current sensing is _still_ wrong... The resistor needs to be *in the power path*. Here I've done it correctly for the overall sensing, notice how there is no named power rail like +BATT, +12, etc before the resistor and only _after_ the resistor does it become +12V.
image
And here it is done correctly for the 5V line, again power flows _through_ the resisor and only then becomes the +5V rail.
image
6. Not sure why the datasheet labels them differently but looks to me like pins 9, 10 and 11 of the 12->5 converter are all outputs so we should probably use all of them. Based on the picture seems like they are shorted on the PCB too.
7. I'd recommend dropping the 12v bulk capacitor down to something like 22 mF (maybe put 3 in parallel and then we can DNP two unless we have issues), since we'll have a decent bit of trouble connecting anything bigger (we're getting into "screw it in" territory here, around 22 mF is on the edge of through-hole).
8. You should multiply all those voltage divider values by 100 so we aren't needlessly drawing power.
9. You have duplicated 12v dividers.
10. Double check the calculations on those voltage dividers. I think we said we wanted to keep the divided voltages under 4V, but for example the 12V divider is outputting 12 / (1 + 2.2) * 2.2 = 8.25V. The 24V resistors also look wrong. I think you've just built all of these upside down?

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
See above

**Review by BluCodeGH — APPROVED** [review]
Nice work! Feel free to proceed with assigning footprints and layout. A couple nits to fix along the way:

1. `ACPowerSupply` and `BatteryPowerSupply` should be net labels, not global labels
2. On your screw terminals to DAQ `INPUT_VOLTAGE` isn't connected to anything.
3. The -12V ATX connection is missing the NC flag
4. I'd refrain from the weird mix of underscores and dashes you're using for the sense lines and call them eg `5V_SENSE+` and `5V_SENSE-`.

**Review by BluCodeGH — APPROVED** [review]
Looks great, I really like how you've organized the split up schematics with kicad. Two small things to fix:

1. Your LED/resistor pairs need values.
2. J13 should probably just be a 3-pin, we don't want to accidentally hook up to +BATT and overload the measurement circuitry.

**Review by JekkuC — CHANGES_REQUESTED** [review]
Throughout your schematic, could you annotate the caps/resistor/connectors/etc.? 

image

They should be labelled so we can reference them.

Also for this one, where is J8 and J9 being connected to? 

image

**Comment by eliaskountouris** [comment]
J8 and J9 connect to the other connectors on other boards. They are just terminal connections, so +12V goes straight to the connector board while the rest go to another board

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Input board review:

1. No shot F1 can handle 25A, you'll definitely want to use the same fuse block that we use on actuator board.
2. Looks like you've selected right angle connectors to the power supply but right now they are all facing into the board and so will collide with your capacitors/relays. In my experience vertical connectors will probably be easier to work with in general tho.
3. D1 has the wrong footprint.
4. C1 probably has the wrong footprint? lmk if you've sourced a 100u cap with the necessary voltage rating (like 35V probably) in 1206
5. Again F2 probably needs that same fuse block from actuator board
6. I'm suspicious about the packages of R1 and R4, pls try to source resistors and update as necessary.
7. I'd recommend putting U1 and C7 on the back as well, they will be pretty much inaccessible on the front nestled between all those massive components.
8. I'd recommend routing your connections around SF1 / F1 / ICL1 / K1 on both sides of the PCB for extra copper to interface with those through holes.
9. The LEDs should be 1206, the corresponding resistors should be 0805.
10. R3 and R5 should be 0806, nothing on the team is 0402 lol
11. The 24V and 5V converters both need to run off of the +BATT output screw terminal, that trace is _way_ too small.
12. Rounded corners are sexy
13. See our conversation about changing up the connectors going to the other boards. I'd also recommend adding another fan connector to this board and removing the one on the connector board, since why spread them out.

**Review by BluCodeGH — COMMENTED** [review]
Connectors board review

1. This board could be a lot more compact if we used 45 degree screw terminals. You could  have a nice big grid of them, which would also simplify your wiring.
2. Missing mounting holes, rounded corners are sexy
3. I wouldn't label the screw terminals here with what they are for, it will change over time and they are all identical anyways.
4. Your 12V trace is much higher priority than your 5V trace so it should be the one traced out manually, not left to a fill that has to skirt around the edges of the board.
5. This board's power input should be a 2-pin +12/GND connector from input board and a 3-pin +24/+5/GND connector from converter board.
6. No need for the fan connector here.

**Review by BluCodeGH — COMMENTED** [review]
Converters board review:

1. Pls use 0805 footprints for basic passives.
2. F3 and F4 should use the same holder as actuator board / the other GSPD boards for consistency
3. Again I'm a bit sus about the footprints of R7 and R9, pls source the specific part and confirm.
4. LEDs should be 1206. That's the size we stock in the bay.
5. Update based on our discussion about connectors.
6. C14, C15 might need to be bigger than 1206 for a high enough voltage rating.
7. Rounded corners are sexy.

**Comment by BluCodeGH** [comment]
Overall all boards are missing team logo, the board name, your names and the date on the silkscreen. Also while you're updating connectors just be aware of how the boards are going to fit together in the briefcase, ie if possible avoid putting screw terminals with really fat wires that will just be pointing straight at a wall.

**Review by rdakhil — DISMISSED** [review]
Converters board:
1. Current sense amplifiers (U4 and U5) should be routed a bit more carefully than other circuits, there is a special way to route to the shunt resistor called "kelvin sensing". There is a section in the INA180 datasheet about this (9.4.2 Layout Examples) showing an example of good current sensing routing practices
2. I would double check the footprints of your shunt resistors, I don't see any available on Digikey in 1206 size. They are usually quite large
3. I think maybe the footprints of D6 and R12 (and D6 and R8) should be swapped?
4. Double check that those fuses are available in 0805 size on Digikey (or in the bay), there might not be a large selection in that size

Connectors board:
- no comments

Input board:
1. Again I think D3 and R2 / D4 and R6 footprints should be switched
2. Same comment about the current sense amplifier routing as the converters board. And C7/C8 should be closer to their current sense amplifier pins (also shown in the datasheet)
3. Same comment about the shunt resistor and fuse footprints
4. Damn, that is a lot of capacitance on the 12V rail. Maybe it is worth considering adding a bleed resistor (on the order of 10k ohms) as a safety feature to discharge those caps 
5. not really important but the back of the PCB might look nicer if the gaps were filled with a ground pour, and then placing some vias to stitch the front and back ground pours together

**Comment by eliaskountouris** [comment]
@BluCodeGH 
Input:
1 - 5: Changes implemented
6: Was able to find may resistors on digikey
7: Done
8: New layout resolves this
9-11: Done
12: Will do tomorrow, need to figure out how to do that
13:  Fixed connectors, but I think its best to leave the fan connectors separate, since 12V fans don't normally have connectors long enough to reach the opposite side of the case.

Connectors:
Will resolve tomorrow

Converters:
1,2,4,5,6: Done
3: Same as Input board #6
7. Same as Input Board #12

Silkscreen stuff (Name, logo, etc) will come once layout is finalized.

Needed to add bleeding resistor and fix ground pour. Will do that tomorrow.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Input Board:

1. Previous point 2 re: right angle PSU connectors is not fixed.
2. D1 GND pad is not connected.
4. I think you probably looked for 16 mR rather than 1.6 mR resistors. There are no 1.6 mR resistors in stock on digikey. I'd recommend switching to a 1 mR 2512 package rated to at least 2W.
5. Daisy chaining through C8.
6. You should definitely disable thermal reliefs for your pours.
7. J1 isn't connected. Please check DRC lol.
8. Missing the bleed resistor Randy pointed out. I'd also maybe suggest only having footprints for 3 caps and starting out by only placing one, even 3 is a scary amount of energy (they would take about half an hour to discharge through even a 1kohm resistor). That lets you cut down on board size too.

Converters board:

1. C10, C11, C12, and C16 are still 0603.
2. Pours thermal relief should be disabled.
3. Same point as before with your shunt resistors, 2512 is recommended.
4. Daisy chaining thorough C9, C13

**Comment by eliaskountouris** [comment]
Input Board:
1. Done
2. Done
3. Can't find any 1.6mR, so I'm going to use 1.5mR. Using 2512 footprint.
4. This is in the recommended layout from the datasheet
5. Done
6. Done
7. Done

Converters board:
1. Done
2. Done
3. Done
4. This is in the recommended layout from the datasheet

Connector Board:
1. Done, double check the layout that they are the correct orientation though. Pretty sure I got it right.
2. Done
3. Done
4. Done
5. Done
6. Think its better for airflow to have a fan on each side of the case, and this way we won't have to have a long cable running very far

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Input Board:

1. Add a date to the silkscreen pls
2. You should label your LEDs with what they indicate.
3. There's a right angle in the trace right under the +5V in connector.
4. The whole right edge of the board is unused, can you shrink the board outline so the PSU connectors are at the edge?
5. The INA180 datasheet's suggested layout unfortunately doesn't take into account the need to be hand-repaired in the desert. If we daisy chain and that pad rips up then the board is much harder to salvage. I'd suggest just moving the vias over to between the capacitor and the INA180. Following the suggested layout is beneficial but it's not a "do exactly this or it won't work" most of  the time.
6. You're missing the GND connection from input board to the connectors board. To prevent us having to do any splicing I'd make J8 have 4 pins - +BATT, GND, +12, GND.

Converters Board:
1. Same point about daisy chaining
2. Same point about date

Connectors Board:
1. Same point about date
2. You probably don't want thermal reliefs on your pours
3. That trace to M2 is going to mess up the +24V pour. I'd move M2 to be right where the silkscreen is currently so it can have nice short traces.

Otherwise everything LGTM, nice work!

**Review by BluCodeGH — APPROVED** [review]
All LGTM! Two tiny things to fix:

1. Diodes on converter board could also use text labels.
2. Converter board pours don't quite go to the edges so it looks bad.

**Review by JekkuC — APPROVED** [review]

**Pull request merged**
