### PR TITLE
Texas powerbox regulator/switch boards

### PR DESCRIPTION
**Pull request by Rio6**
This boards takes 24V from either an adapter or battery and outputs it to USB and Misumi connectors.

圖片

### CODE REVIEW

**Comment by ZTeper** [comment]
The 5V regulator has a max output current of 100 mA. Is that enough?

**Comment by Rio6** [comment]
> The 5V regulator has a max output current of 100 mA. Is that enough?

Hm I'm actually not sure how much current USB usually use. I can look on digikey for one the gives more current though.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
1. I'd rename the folder from `kicad` to `schematics`
2. In addition to that 5V regulator I think that the mosfet is underpowered. A conservative estimate for the maximum overall current draw is 10A (5A for the lights, 3A for DAQ, 2A for USB).
3. I got that USB number by looking at the usb 2.0 spec, which dictates a maximum of 500ma per port. There are lots of buck converters that can do 5V 2A on digikey. Might be better to get a 3 or 4A one just to have some breathing room with the 5V lines on the misumi connectors.
4. Definitely need fuses on the input and each usb port (can use 750ma PTC fuses for them)
5. I'd recommend 277-1248-ND for your power output connector (and the 2-pin version for input).
6. That switch looks a bit dinky, I think a nice solid throw switch would be good (we have some in the bay, I'll get you a part number)
7. Do you know how the LTC chip will act if the battery voltage is higher than the adapter voltage? We want it to use the adapter voltage even if the batteries are charged more.
8. It would be good to hook an LED up to STAT so we can tell what power source it's using.
9. GND and the 24V plug are not connected.
10. You can spread out the power select schematic a bit, eg it's not clear rn that the mostfet part number isn't for the diode.

**Comment by BluCodeGH** [comment]
Oh also a power indicator led would be great, probably easiest on the 5v line.

**Comment by Rio6** [comment]
> 1. I'd rename the folder from `kicad` to `schematics`

:+1:

>     2. In addition to that 5V regulator I think that the mosfet is underpowered. A conservative estimate for the maximum overall current draw is 10A (5A for the lights, 3A for DAQ, 2A for USB).

Switched to 785-1836-ND

>     3. I got that USB number by looking at the usb 2.0 spec, which dictates a maximum of 500ma per port. There are lots of buck converters that can do 5V 2A on digikey. Might be better to get a 3 or 4A one just to have some breathing room with the 5V lines on the misumi connectors.

Switched to LM338T-ND for regulator. Also, didn't think to look at usb spec, good to remember such thing exists :P

>     4. Definitely need fuses on the input and each usb port (can use 750ma PTC fuses for them)

Added 12A for input and 600mA for each USB

>     5. I'd recommend 277-1248-ND for your power output connector (and the 2-pin version for input).

Added

>     6. That switch looks a bit dinky, I think a nice solid throw switch would be good (we have some in the bay, I'll get you a part number)

Switched to 360-2996-ND

>     7. Do you know how the LTC chip will act if the battery voltage is higher than the adapter voltage? We want it to use the adapter voltage even if the batteries are charged more.

It only switched battery off if aux voltage is >20mV more. I might need to look for another one.

>     8. It would be good to hook an LED up to STAT so we can tell what power source it's using.

Added a power led on 5V line. STAT will need to be changed due to point 7

>     9. GND and the 24V plug are not connected.

Where?

>     10. You can spread out the power select schematic a bit, eg it's not clear rn that the mostfet part number isn't for the diode.

:+1:

**Review by BluCodeGH — COMMENTED** [review]
3. That regulator says its not recommended for new designs on digikey, are there good alternatives?
4. We already stock 750ma PTCs so you're probably fine to use them, the main concern here is a short down the line so the exact value isn't super important. We also stock 10A fuses, realistically I expect this to be nowhere near that for the time being so probably easiest for whoever's assembling this if we mark it as 10A.
5. I think it's a better idea to use a DIN rail to distribute power and have a single terminal block output on the board.
7. Yeah we'll need to find a more optimal chip or circuit.
9. Seems to be fixed anyways.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great!
11. I think you need a PMOS mosfet in that configuration. See the wonderful explanation of how mosfets work pinned in #electrical by Aaron, you might want to switch to low-side switching. Also best to orient your mosfets as he recommends for readability.
12. Tiny nit but would be better to have each of the output screw terminals have one GND and one +V, so they're a bit more independent.
13. Please add text either saying where you got those part values for the DC/DC regulator or showing calcs.
14. Also no need to stick the same diode, I guess fine it you want to though.
15. Might be a bit cleaner to use separate GND flags for the DC converter circuit rather than using a wire.
16. Fine if you want to use power flags but no need to worry about them, we usually just ignore those DRC complaints lol.

**Comment by Rio6** [comment]
11. I recreated it in Falstad simulator and NMOS looks right. I have to use high side switching because both power sources needs to share the same ground for the BJT to switch right. But it does seems like it'll have quite a bit of voltage drop so might need to find yet another design.
12. fixed
13. It's from TI's Webench, I added the link to it (although I'm pretty sure it'll require an account to see).
14. yeah didn't want to hunt for yet another part :p
15. Tried fixing it a bit, it now has one less intersection
16. I just don't like to see ERC complaining XD

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
15. I still think something like this is easier to read, especially if you edit the pin layout of the IC so GND is at the bottom and COMP is below VSENSE, but up to you.
image
16. Ugh github doesn't let me skip a number in a list.
17. What's the purpose of D3 and D4?
18. You could maybe move SW1 to be below the battery connector and then have it go to a separate GND flag.
19. That relay has a 'must operate voltage' of 36V, we're going to be trying to drive it with 24. Probably best to find an alternative. Maybe we can use the same relays as towerside?
20. The 5V LED should go after the fuse so we can easily tell it's blown.

**Comment by Rio6** [comment]
15. Fixed
17. Reverse polarity protection. I used diode for D3 because I had a big capacitor there before and it also helps preventing it discharging back to battery when switching. I can probably replace it with mosfet now.
18. Fixed
19. Replaced with 2449-J107F1CS1224VDC.36-ND
20. Fixed

**Comment by Rio6** [comment]
Replaced D3 with mosfet

**Review by BluCodeGH — APPROVED** [review]
21. Good idea to add a text comment saying what the mostfet and D3 are doing.
22. On that thought, good to add a text comment saying the intended function for each combination of battery or adapter connected.
Looks good, maybe get another set of eyes on it an then move onto the pcb.

**Review by QuantumManiac — APPROVED** [review]
LGTM, should be fine to proceed to layout

**Review by BluCodeGH — APPROVED** [review]

**Review by QuantumManiac — APPROVED** [review]

**Review by zx100x100 — CHANGES_REQUESTED** [review]
Looks pretty cool, I see two main changes:
1. looks like you are using low side switching on this power supply, this isn't a good idea for much more than valves, lights, or any other simple electrical device. In this case disconnecting the ground from your power regulator will result in undefined behavior, most likely case is that it will end up holding all devices on the 5V line at 24V. That would mean that if anyone inadvertently grounds them, they would likely be fried, so definitely switch to having the main power switch on the high side.
2. it doesn't look like there is any sort of voltage sensing for the battery right now. I'm not sure exactly what it should look like, maybe just a little 7 segment voltage monitor module. (these types of things https://www.amazon.ca/Digital-Voltmeter-Two-Wire-2-5V-30V-Voltage/dp/B07KY5TRTH/ref=asc_df_B07KY5TRTH/?tag=googleshopc0c-20&linkCode=df0&hvadid=292923635907&hvpos=&hvnetw=g&hvrand=14796943555149731012&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9001597&hvtargid=pla-639484037443&psc=1)

but experience has shown, not having an easy way to keep an eye on battery voltages can cause big problems and annoyances.

**Comment by Rio6** [comment]
1. Having multiple sources makes it a bit hard to do high side switching. I think I'll need to use a DPST switch for that.

Edit: something like this might work?
圖片


2. Ok I can add one in

**Comment by Rio6** [comment]
圖片

actually, something like this for switching might work?

**Review by BluCodeGH — APPROVED** [review]
That looks right to me.

**Comment by Rio6** [comment]
Looking at my current layout, I think I can move voltmeter connector to a 24v din rail to keep the board smaller.

**Review by rdakhil — APPROVED** [review]
Looks goods to me! My only suggestion is that it might be nice to put a note of the operating output current of the buck regulator.

**Pull request merged**
