### PR TITLE
New converter

### LINKED ISSUE #7: +24V rail cannot provide enough power to run the full CAN bus
We didn't account for the power requirement of on-the-pad charging in this design, which may need to power the entire rocket (approximately 15 W @ 24V).

### PR DESCRIPTION
**Pull request by ManavToor**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/infrastructure/11)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking like a good start! Some things to fix:
1. You symbols dont have to (and generally are better of not) matching the physical pin layout of the IC. The +5V regulator does a bad job at this but some things you can do are
    1. Combining duplicated physical pins into a single 'logical' pin. You do this by overlapping the pins in the symbol and setting all but one as hidden. You should do this for the PGND and SW pins.
    1. Moving things around so that the schematic is layed out better. For example, I would strive to have your schematic look like the typical application on the first page of the datasheet, which is a fairly standard layout and thus easier for people to understand. The only change I'd make to that typical application is since we're combining the SW and PGND pins, you can move some of the other pins (eg FREQ and SS) to the right side to keep things tidier.
1. Power symbols (+BATT, +24V, etc) should always point upwards, not downwards like you have. Only GND should  point downwards.
1. You main output capacitor should be before the fuse and sense resistor, you want it as close as possible to the converter to reduce noise most effectively.
1. This schematic uses an unholy mix of R_US, R, and R_Small_US symbols. We should switch everything to R_US which is the team's standard.
1. Also you should switch the LEDs to the normal LED symbol, not LED_Small.
1. I'd personally recommend using individual GND symbols for everything that needs it rather than having a common GND wire like you do now. I find having the common line stretches everything out awkwardly and makes things look busier than they need to be.
1. According to the first page of the datasheet the max frequency is 1.2 MHz, but you current have it set as 1.8 MHz. The application secton of the datasheet recommends 600 kHz which seems reasonable to me.
1. Going through the inductor calculations I think we should pick Kind = 0.2, so I calculate that we should probably use a 10 uH inductor at 600 kHz?
1. You should source part numbers for your inductor, diode and fuse and put them as the 'Value' field.
1. How did you calculate the input and output capacitor values? The ones you've chosen look quite big. Also keep in mind that big capacitors will need to be electrolytic which means a high ESR, so using multiple smaller ones in parallel is generally preferable.
1. According to page 18 of the datasheet the lower feedback resistor should be 10k, not 1k.
1. In general, including the parameters required to calculate your component values is a good idea so other people can follow through the datasheet and check your work.
1. Both fuses are using the polyfuse symbol but I believe they are plain old fuses, please fix the symbol.
1. The sense resistor can currently only sense up to 1.25A with the 100V/V gain and 5V limit of the INA180. Also please add an "R" suffix to decimal resistor values, eg "0.02R".
1. You can just use "k" as a suffix for your resistors, you dont need "kOhm". Looks like some of the old resistors use a capital "K", we should also fix those to be lowercase.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
This is looking much better, nice work. Your part values look reasonable, but you should include a text note on the schematic giving the key parameters I need to reproduce your numbers (output current, K_ind, n_est, etc.). A couple other minor things I spotted
1. 1400pF is not a standard capacitor value so you're going to have a hard time finding one. Pick a standard value that's close by.
2. Make sure you have the correct footprint for your inductor, right now I don't think it matches.
3. We probably want to use the same fuse footprint as the 5V one, this is a catridge fuse holder so we can easily swap out the fuse if it pops without needing to disassemble and resolder a SMD fuse. SMD fuses are only really good for flight boards where space is a big constraint.
4. Both LED resistors are missing values.
5. Make sure all of your resistors/capacitors/diodes/etc have footprints assigned. Also make sure those footprints are 0805 (or 1206 if you cant find anything in 0805), right now I see some 0402 parts which will be totally impossible to solder by hand.

Feel free to get started on PCB layout once the above is addressed.

**Comment by DomenicHampson** [comment]
Hey Manav looking good so far. Some changes...


1. On the top layer, you created a gnd pour which means that entire top surface is gnd and therefore you do not have to connect the GND pins to each other. On the top I recommend you instead do either a +BATT or +24V pour since we expect a lot of current going through and will need a lot of COPPER (see how this is done on the back side of the old GSPD board with +BATT).

(Related to the above)
2. A big thing to consider for this board is the current draw. You will need to adjust the width of the traces where we expect more current (for example the +batt input). Go through the pcb and determine which traces need to be adjusted, how much current we expect going through them and use an online calculator to determine the width.

3. On the bottom layer, you have a pour but didn't select what type. I would set this one to GND and again you don't have to route GND pads. 

4. Not a big deal but I'd redraw the bottom pour outline so that it looks nicer.

5. Kinda unrelated but did you source vertical screw terminals as opposed to horizontal?

6. Also keep in mind the location of the screw terminals, they need to be positioned for close connections with the other boards inside GSPD. I would take a look inside GSPD when you get the chance.

7. What is the new fuse value on the 24V line? Can you edit the schematic to specify it.

8. Just realized we missed the mounting holes, you will need to add them to the schematic and then select the same footprint used in the original converter board. Make sure they align perfectly with the original. Also make sure they all provide a path to the GND pour on the bottom side.

9. We should also add some test points for the voltage lines and batt cause why not (will also have to add them to the schematic first)

10. Be sure to add the waterloo rocketry logo, project name and your name to the board (refer to other boards)

It's late and I'm tired so address these for now and I'll give another look when you are done. Thanks!

**Comment by ManavToor** [comment]
I ended up redoing the layout all together to make it more organized, hopefully there are less issues with this one

**Review by DomenicHampson — CHANGES_REQUESTED** [review]
Looking great just a couple small changes...

1. Avoid right angles with your traces. Using right angles for traces can lead to signal integrity issues and electromagnetic interference, so it's generally avoided in PCB routing.
image
image
image

2. Make sure you are using the same mounting holes used on other boards. This is what they look like on GSPD connector board
image

3. These traces here do not have to be thick. There will be minimal current flowing through those traces.  Same for the test points.  I would double check all your traces confirming which ones actually need to be beefier.
image
image

4. Also about the test points, I would group them together on the board.

5. I would move all components to the top side so we can see them when this board is mounted.

6. Are you sure your routes are thick enough? We should have them wide enough to be able to handle up to 3A since that is our fuse value. I see your routes are 0.93mm thick but from a google search they should be 1.27mm. How did you do the calculation for your route thickness? 
image

7. Also kinda related, I would double check to make sure the connection between L1 and +BATT plane (and others alike) are thick enough to handle the max expected current.
image

That's all for now thanks!

**Comment by ManavToor** [comment]
Fixed all the traces, I was calculating for 2A not 3 by mistake. There should also be no more right angle connections.

I am using the same mounting hole, I just chose one with via's because it looks cooler but the dimensions are the exact same.

Test points are all grouped together now.

I found and imported a footprint for the inductor from mouser. Almost forgot about that lol.

**Review by DomenicHampson — CHANGES_REQUESTED** [review]
Hey Manav almost there...

1. This guy doesn't have to be chunky.
image

2. There a couple 90 deg traces still
image
image
image

3. Move the batt testpoint over so it is aligned
image

4. I forget what is the 5V in for again?

Thanks!

**Comment by ManavToor** [comment]
All 90 deg traces have been eradicated!

Aligned the batt test point

5V is for op amps

**Review by DomenicHampson — DISMISSED** [review]
Looks good thanks!

Just stitch this trace here so the power plane isn't cut in half.
image

Lets get some more eyes on this too before ordering.

**Review by DomenicHampson — DISMISSED** [review]

**Review by StarlightDescender — CHANGES_REQUESTED** [review]
1. Still some issues that the DRC is raising - some of the text is slightly too short (and also smaller than what JLCPCB has as a minimum), and there's an unconnected pair of 5V lines - all you need to do is add a via here. 
image
2. 
image
Shouldn't this use the thermistor symbol rather than the regular resistor symbol?
3. Missing datasheets for the inductor and diode
4. There's still a lot of daisychaining, and there's so much space on the board.
image
image

**Comment by ManavToor** [comment]
1. Good catch on the text. For the traces, DRC was picking up on remnants of old traces that I just laid new traces on top of. But I deleted them all
2. Yes it should
3. Not anymore
4. Shouldn't be an issue with gnd. Second one is not daisychaining, trace on the left is feedback and the right trace is a decoupling cap

**Comment by Joe-Joe-Joe-Joe** [comment]
I would disagree with your above assessment - those GND pads is actually one of the few times where I think daisy chaining is even a valid concern, since you could have pad 14 come off and still tie pin 14 to ground by shorting the other pins to it and retain functionality

**Comment by Joe-Joe-Joe-Joe** [comment]
Also new gerbers and sch PDF pls

**Comment by ManavToor** [comment]
Did not realize pads coming off was even possible. Removed the daisy chaining, added gerbers, and a schematic pdf. I don't know if this applies but i put a "JLCJLCJLCJLC" silkscreen under an ic

**Comment by Joe-Joe-Joe-Joe** [comment]
I know this is a pretty ridiculous ask given the current state of the project, and nothing stops me from looking at a PCB and telling you if it is designed well or not, but can we have some documentation as to... what this does? Like theres a top level kicad project and then 3 subprojects and I had to work backwards to figure out which one i was even reviewing. I know that the GSP box takes in Lead acid battery and 120 VAC power and spits out 24V, but I know literally nothing else about it.
Edit: I figured out why where is more than one project file... I think?

**Comment by Joe-Joe-Joe-Joe** [comment]
1. In order to keep them accurate, you should route current sense resistors like this
see https://electronics.stackexchange.com/questions/617091/kelvin-connections-in-pcb
image
2. DRC Error? Unconnected pads? I don't really know what's going on here
image
3. Please label your connectors with what they do. Currently I could not tell you which one of these "+5"s is current sensing, power in, and power out.
image
4. Please rotate component refdes on silkscreen to face one consistent direction. Connector silkscreen labels should remain facing outward like you have them
5. Pins 1/2 of the boost converter are, as far as I can tell, high current lines, similar to pins 1/15/16 in this example layout. You currently have 0.25mm traces running out of them. Also, routing guidelines suggest that the length of SW lines should be as low as possible
image
6. Likewise, all your ground lines on the boost converter need to be thicker. And that big fat thermal pad should be tied to ground according to the datasheet and example layout. Since your ground pour is on the opposite side, you need a GND pour around the thermal pad and thermal vias to the opposite board side

**Review by Joe-Joe-Joe-Joe — CHANGES_REQUESTED** [review]
see above

**Comment by ManavToor** [comment]
1. Done
2. One 5V is to power the op amps, the other 5V is the buck converter output. I kept the lines seperate, which is why kicad is throwing an error 
3. Done
4. Done
5. Switched SW to a cu pour and moved it closer
6. Done

**Review by Joe-Joe-Joe-Joe — DISMISSED** [review]
Some of the silkscreen are still rotated different ways. But idc, it's electrically sound. LGTM

**Review by DomenicHampson — CHANGES_REQUESTED** [review]
Looks good. Just a few things to clean up the board and then it LGTM

1. If you run the DRC you will several track's with unconnected ends. Please clean those up.

2. As Joe mentioned, there are several component silkscreen labels not aligned consistently. For 2 pad components like caps and res, I like to have the label parallel to the component. Some labels that shuld be rotated are... C2, R2, R3, R13, R5, R7 and F2

Thanks!

**Comment by ManavToor** [comment]
Fixed the silkscreens

Not seeing the DRC error though, all I have is a couple of silkscreen warnings

**Review by DomenicHampson — APPROVED** [review]

**Review by BluCodeGH — APPROVED** [review]
Not sure why all your capacitors are using diode footprints but electrically LGTM, I wouldn't bother pushing to fix tbh.

**Pull request merged**
