### PR TITLE
Texas Powerbox PCB

### PR DESCRIPTION
**Pull request by Rio6**
圖片

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great!
1. DRC has a few complaints for you to fix
2. Maybe make the 24V and 5V silkscreens a bit bigger so they are more visible? Also the fuse value silkscreens will be hidden by the blocks, best to move them outside the footprint.
3. Nit but you have a couple right angle traces that would be easy to fix
image

**Review by BluCodeGH — APPROVED** [review]
- Tiny nit that the holes aren't symmetrically distant from the top and bottom of the board, also please add measurements of the board size + hole pattern on the drawings layer.
- You should also probably give this board a name (make something up, eg remote arming is called 'sushi' iirc). I'd replace the silkscreen 'Waterloo Rocketry' with the name.
- Lastly best to wait for a few more :eyes: before merging.

**Comment by Rio6** [comment]
I swear I aligned the holes once already...

also I named the board Grape

**Review by QuantumManiac — APPROVED** [review]
LGTM - I love the name. It would also be nice to put the date the design was created on the PCB - perhaps below your name and the PCB name - in YYYY-MM-DD format. Additionally, it might be worth changing the PCB name silkscreen from "Grape" to "Grape v1" for revision reasons.

Additionally, out of curiosity, what's the point of these two zones? Test points?
image

**Comment by Rio6** [comment]
I'm thinking to add extra solder blob to those two connections for extra current capacity. That would work right?

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Sorry, one thing I missed. Please add board dimensions and spacing between mounting holes. Example from another board below: 
image

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
A few cleanup tasks:

- Please remove the old kicad 5 files (.pro and .sch, along with the .sch-bak).
- Add the kicad backups folder to the .gitignore (add the line `/*-backups`).

Last thing to do before merging this, please add all of the components this board will require (export the BOM from tools->generate BOM->bom_html_with_advanced_grouping) to the [master electrical orders spreadsheet](https://docs.google.com/spreadsheets/d/1BueiN9HmC8HtrSg3OIwg5nm5VYwdf4eYnYHdHctQ7GE/edit?usp=sharing), make sure to find digikey part numbers that are in stock.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
New design looks good, a couple super minor tweaks:
1. It's always best to do the calculations a datasheet suggests rather than copying the example part values. In this case I calculate that L1 should have a value of 6.6 uH (equation 11), that the total input capacitance should be ~20 uF (rearrange equation 13, I guessed at 100 mV noise). For the output capacitor what you have is probably fine, it would lead to about 5mV noise which is acceptable.
2. Your 4A fuse silkscreen is off the edge of the board
3. Also stick with grape V1 until we order the board :stuck_out_tongue: 

Last up please generate gerbers, JLC has a tutorial https://support.jlcpcb.com/article/149-how-to-generate-gerber-and-drill-files-in-kicad which is for kicad 5 but should be mostly followable, lmk if you have any questions. We usually put them in a gerbers/ folder in the kicad project.

**Review by rdakhil — COMMENTED** [review]
Looks great! Just a few comments:
1. Silkscreen hanging off the edge of the board below F2: 
image

2. I would place C1 closer to the input pin of the buck regulator. As a general rule, input caps should be placed as close as possible to the input pin

3. I would also recommend you set pad 9 of the buck and the through-holes on top of it to the GND net, and also connect the unfilled area around it to GND using VIAs, something like this:
image

DC-DC regulators can sometimes generate a lot of heat, so connecting the buck to a GND plane will help dissipate it

**Review by BluCodeGH — APPROVED** [review]
F2 silkscreen looks correct on my end. Apart from those other two points LGTM!

**Review by ZTeper — APPROVED** [review]

**Comment by ZTeper** [comment]
Please also label "+" and "-" silkscreen labels on each DC power connector

**Review by QuantumManiac — APPROVED** [review]

**Review by rdakhil — APPROVED** [review]

**Review by LanaTomlin — APPROVED** [review]
love the fat traces

**Comment by BluCodeGH** [comment]
Ordered, merging.

**Pull request merged**
